steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nome-do-seu-servico:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nome-do-seu-servico:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'nome-do-seu-servico'
  - '--image=gcr.io/$PROJECT_ID/nome-do-seu-servico:latest'
  - '--platform=managed'
  - '--region=us-central1' # Substitua pela sua região preferida